### ISSUE TITLE
object 'QWizard' has no attribute 'WatermarkPixmap'

### ISSUE THREAD

**Issue by yaoberh** [migaku-official/Migaku-Anki-Addon#36]
```
Debug info:
Anki 2.1.51 (51a0641b) Python 3.10.4 Qt 6.2.3 PyQt 6.2.3
Platform: Linux
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2022-04-15 21:23:21
Add-ons possibly involved: ⁨Migaku Anki Add-on⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/main.py", line 339, in onOpenProfile
    self.loadProfile(on_done)
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/main.py", line 462, in loadProfile
    gui_hooks.profile_did_open()
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/hooks_gen.py", line 3071, in __call__
    hook()
  File "/home/yaoberh/.local/share/Anki2/addons21/1846879528/welcome_wizard.py", line 45, in check_show_modal
    wizard = cls()
  File "/home/yaoberh/.local/share/Anki2/addons21/1846879528/welcome_wizard.py", line 31, in __init__
    page = wcls.wizard_page()
  File "/home/yaoberh/.local/share/Anki2/addons21/1846879528/settings_widgets.py", line 64, in wizard_page
    return cls.WizardPage(cls, parent, is_tutorial)
  File "/home/yaoberh/.local/share/Anki2/addons21/1846879528/settings_widgets.py", line 26, in __init__
    self.setPixmap(QWizard.WatermarkPixmap,
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/qt/qt5_compat.py", line 350, in __getattr__
    return getattr(type, name)
AttributeError: type object 'QWizard' has no attribute 'WatermarkPixmap'

```

**Comment by RicBent** [comment]
Thanks for the report.

Fixed with https://github.com/migaku-official/Migaku-Anki-Addon/commit/4babfa135efdb77e48aa10bb9c2dd6fc0e9ebeae
This will be included in the next release.
