### ISSUE TITLE
Anki addon doesn't get work correctly and cannot be used by extension

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Anki-Addon#45]
```
Une erreur est survenue. Veuillez démarrer Anki en maintenant la touche majuscule enfoncée, ce qui désactivera temporairement les greffons que vous avez installés.
Si le problème ne survient que lorsque les greffons sont activés, veuillez utiliser le menu Outils > Greffons afin de désactiver certains greffons. Redémarrez Anki jusqu’à ce que vous découvriez le greffon qui cause le problème.
Une fois ce greffon découvert, merci de signaler le problème sur le site de support du greffon.￼
Information de débogage :
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-18 16:43:55

Caught exception:
Traceback (most recent call last):
  File "C:\Users\josht\AppData\Roaming\Anki2\addons21\1846879528\migaku_connection\__init__.py", line 32, in run
    self.server.listen(44432, reuse_port=True)
  File "C:\Users\josht\AppData\Roaming\Anki2\addons21\1846879528\lib\shared\tornado\web.py", line 2109, in listen
    server.listen(port, address, reuse_port=reuse_port)
  File "C:\Users\josht\AppData\Roaming\Anki2\addons21\1846879528\lib\shared\tornado\tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address, reuse_port=reuse_port)
  File "C:\Users\josht\AppData\Roaming\Anki2\addons21\1846879528\lib\shared\tornado\netutil.py", line 87, in bind_sockets
    raise ValueError("the platform doesn't support SO_REUSEPORT")
ValueError: the platform doesn't support SO_REUSEPORT
```

https://discord.com/channels/752293144917180496/856003979695095838/1108993820428877834

**Comment by hgiesel** [comment]
This was fixed by:
https://github.com/migaku-official/Migaku-Anki-Addon/commit/04433bce40be925589aa3e65b66f5b625b293978#diff-7cdcc48def5bbe15eda31570a12afae27264593bf36a984dcfb932699df313efL32

However fixing this gave rise to #47
