### ISSUE TITLE
this platform is not supported: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import)

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Anki-Addon#46]
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Migaku Anki Add-on⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/__init__.py", line 38, in <module>
    from . import (
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/welcome_wizard.py", line 9, in <module>
    from .global_hotkeys import HotkeyConfigWidget, hotkey_handler
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/global_hotkeys.py", line 4, in <module>
    import pynput.keyboard
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import) (/Users/jasonshi/Library/Application Support/Anki2/addons21/1846879528/lib/macos_39/objc/__init__.py)

Try one of the following resolutions:

 * Please make sure that you have Python bindings for the system frameworks installed
 ```

Further reports: 
* https://discord.com/channels/752293144917180496/944336185029971978/1113209120129040566
* https://discord.com/channels/752293144917180496/944336185029971978/1112215115174002758
* https://discord.com/channels/752293144917180496/944336185029971978/1110722534099398786

**Comment by hgiesel** [comment]
Delay this until Kanji God Addon is fixed

**Comment by MinmoTech** [comment]
Apparently this can also happen on Anki 2.1.60

https://discord.com/channels/752293144917180496/752296547433185330/1120356455829213184

**Comment by MinmoTech** [comment]
Fixed with https://github.com/migaku-official/Migaku-Anki-Addon/pull/58
