### ISSUE TITLE
[Linux]: Wayland error message

### ISSUE THREAD

**Issue by mainrs** [migaku-official/Migaku-Anki-Addon#77]
```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Migaku Anki Add-on⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/__init__.py", line 37, in <module>
    from . import (
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/welcome_wizard.py", line 6, in <module>
    from .settings_widgets import TUTORIAL_WIDGETS
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/settings_widgets.py", line 10, in <module>
    from .global_hotkeys import HotkeyConfigWidget, hotkey_handler
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/global_hotkeys/__init__.py", line 6, in <module>
    from .hotkeys import HotkeyHandler
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/global_hotkeys/hotkeys.py", line 3, in <module>
    from magicy.keyboard import Key, Controller
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/lib/shared/magicy/__init__.py", line 42, in <module>
    from . import keyboard
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/lib/shared/magicy/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/me/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1846879528/lib/shared/magicy/_util/__init__.py", line 78, in backend
    raise ImportError(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

```

I run GNOME 43 as my desktop environment, which by default runs on Wayland nowadays.

**Comment by carif** [comment]
Same problem on Fedora Linux 41 (GNOME 47):

```
Anki 24.11 (87ccd24e) (src) (ao)
Python 3.12.9 Qt 6.8.3 PyQt 6.8.0
Platform: Linux-6.13.9-200.fc41.x86_64-x86_64-with-glibc2.40
```

KDE Plasma 6 is using Wayland as the default protocol, too.

**Comment by mainrs** [comment]
@carif I "solved" this by installing the flatpak version and then using [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) to deny access to the Wayland windowing system. The Anki flatpak then falls back to X11.

This results in another issue: the flatpak can't connect to the browser extension. I am still figuring that one out...

The proper solution would be to officially support Wayland. Every major Linux distribution has switched to Wayland sessions by default.

**Comment by saraphl** [comment]
May be related to the report I made on [Migaku's discord](https://discord.com/channels/752293144917180496/1431570518196093028) - also regarding global hotkeys on Wayland. This addon uses old version of  pynput library (what's in the "magicy" lib directory) and was likely fixed in its version 1.7.8. The fix is however not as straightforward as simply swapping out the lib files, as this introduces more incompabilities within the addon.
